### ISSUE TITLE
cannot use debbit until a specific date

### ISSUE THREAD

**Issue by xbingnan** [jakehilborn/debbit#40]
INFO: 2020-12-01 07:31:23,029 Bursting next 1 frontwave_credit_card_amazon_gift_card_reload purchase after 2020-12-02 12:00AM
INFO: 2020-12-01 07:31:23,033 Bursting next 1 Navy_Fed_credit_card_amazon_gift_card_reload purchase after 2020-12-02 12:00AM

I set up a reminder to run it 1st of everyone, it seems i need to change the time everytime to run i t again, how can i change the purchase after date? Thank you

**Comment by jakehilborn** [comment]
This behavior is intentional. It is unknown what time your computer uses. It's also unknown what time your financial institution uses. To ensure that the transactions post to the correct month debbit executes purchases between the 2nd day of the month and the 2nd to last day of the month. This way, even in the worst case 23 hour timezone difference, all activity happens in the correct month.

You can modify this by adding this advanced section to your config.txt and setting the min_day to 1.

```
red_debbit_card:
  amazon_gift_card_reload:
    total_purchases: 20
    amount_min: 10
    amount_max: 20
    usr: username
    psw: p@ssw0rd
    burst_count: 1
    card: 1111222233334444
    advanced:
      min_day: 1
```

I know everybody uses software differently so you don't have to do this. But, you could use debbit as was designed to run month to month. Just run it once for December and leave it running. Once it becomes January debbit will start executing purchases again. Same for February and so on. In the getting started section of the [FAQ](https://jakehilborn.github.io/debbit/#faq) there are instructions to ensure debbit auto-starts when your computer starts up. And, debbit will send you email notifications if it ever fails so you don't have to keep an eye on it.
